# Generated by Django 4.2.6 on 2023-10-20 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Courses",
            new_name="Course",
        ),
    ]
