# Generated by Django 4.2.6 on 2023-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_rename_courses_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
