# Generated by Django 4.2.6 on 2023-10-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                default="courses/default_courses_image.jpg",
                upload_to="courses/%Y/%m/%d/",
            ),
        ),
    ]
