# Generated by Django 4.2.6 on 2023-10-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="courses.tag"),
        ),
    ]
